### ISSUE TITLE
public-xar-repo returns bad mime-type

### ISSUE THREAD

**Issue by adamretter** [eXist-db/public-repo#17]
The public package repo at this URL returns content type `text/plain` - http://demo.exist-db.org/exist/apps/public-repo/public/apps.xml?version=3.6.0-SNAPSHOT&source=

Which is incorrect. It should return `application/xml`. I checked the code and it looks okay here: https://github.com/eXist-db/public-xar-repo/blob/master/modules/list.xql#L9

However the result is bad:

```
$ curl -vv "http://demo.exist-db.org/exist/apps/public-repo/public/apps.xml?version=3.6.0-SNAPSHOT&source="

*   Trying 88.80.11.10...
* TCP_NODELAY set
* Connected to demo.exist-db.org (88.80.11.10) port 80 (#0)
> GET /exist/apps/public-repo/public/apps.xml?version=3.6.0-SNAPSHOT&source= HTTP/1.1
> Host: demo.exist-db.org
> User-Agent: curl/7.50.3
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Wed, 01 Nov 2017 19:18:10 GMT
< Server: Jetty(8.1.9.v20130131)
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< Content-Type: text/plain; charset=UTF-8
< X-XQuery-Cached: true
< Set-Cookie: JSESSIONID=4r9prnt0vbr0fm3q7rz0hys7;Path=/exist
< Vary: Accept-Encoding
< Transfer-Encoding: chunked
< 
<apps version="3.6.0-SNAPSHOT">
    <app path="expath-crypto-exist-lib-0.3.3.xar" size="98198">

...
```

Could this be a hosting issue?

**Comment by windauer** [comment]
@adamretter this is definitely a hosting issue I'd say (or a very miss configured eXistdb). I checked on my local computer and the Content-Type is as expected `application/xml`

```
➜  exist curl -I "http://localhost:8080/exist/apps/public-repo/public/apps.xml?version=3.6.0-SNAPSHOT&source=" 
HTTP/1.1 200 OK
Date: Wed, 01 Nov 2017 22:15:28 GMT
Set-Cookie: JSESSIONID=node0hx1lwfy4py1y1w93udj9dryez6.node0;Path=/exist
Expires: Thu, 01 Jan 1970 00:00:00 GMT
X-XQuery-Cached: false
Content-Type: application/xml; charset=UTF-8
Transfer-Encoding: chunked
Server: Jetty(9.4.6.v20170531)
```

I fear I can't help on this since we (eXist Solutions Admin Team) does not have access to the infrastructure although we would be happy to fix (and some other outstanding issues). But afaik only @ljo has access.

**Comment by adamretter** [comment]
@ljo Any comments on this please?

**Comment by ljo** [comment]
@adamretter I get `Content-Type: application/xml; charset=UTF-8` as expected.

**Comment by adamretter** [comment]
@ljo hmm that's interesting I wonder what changed?

**Comment by joewiz** [comment]
Closed by https://github.com/eXist-db/public-repo/pull/27
