### ISSUE TITLE
Rename this repo as "public-repo"

### ISSUE THREAD

**Issue by joewiz** [eXist-db/public-repo#31]
This project is always referred to as "public-repo". Renaming the repository from "public-xar-repo" to "public-repo" would aid in its discoverability. Any objections?

**Comment by adamretter** [comment]
I don't object per se. But I do think both names are just terrible and ambiguous

**Comment by joewiz** [comment]
Okay, the project now lives at https://github.com/eXist-db/public-repo.

Whatever the name is (a different question), it's clearly preferable for app's names to align with their repo's, unless there's a compelling reason that they should be different (e.g., short/legacy URLs for app names vs. longer descriptive names for repos). 

We have some cases like this. To wit:

app | repo
--- | ----
atom-editor | atom-editor-support
doc | documentation
fundocs | function-documentation
wiki | AtomicWiki
