### ISSUE TITLE
Align handling of pre-release and build metadata with semver spec

### ISSUE THREAD

**Issue by joewiz** [eXist-db/public-repo#33]
The public repo ignores pre-release and build metadata. Notice in https://github.com/eXist-db/public-repo/blob/master/modules/scan.xql#L20-L24 that the 4th regex group is completely ignored. As a result, the public repo may well sort "4.0.0-RC1" as *greater than* "4.0.0", whereas according to the semver 2.0 guidelines on how pre-release and build metadata should figure into precedence calculations, "4.0.0-RC1" should be treated as *less than* "4.0.0". (See https://semver.org/#spec-item-11.)

This problem was first observed here: https://gitlab.existsolutions.com/tei-publisher/tei-publisher-app/issues/188.

We could use this opportunity to adopt proper semver handling for packages. Even though the EXPath Package spec references semver, it appears to have been written without strict adherence to semver. However, semver is now the dominant convention for versions in the eXist community. Thus, rather than patching the old code, we could leverage the semver.xqm library at https://gist.github.com/joewiz/b349e2853a17bf817e5d0013d01fa9f9#file-semver-xqm. 

If we adopt strict semver, I think the following actions would be needed:

- The public repo should reject uploaded packages whose version is not a valid semver string.
- Existing packages will need to be reviewed, and handling for packages with non-semver-compliant version strings should be discussed.
- It would also be responsible to propose a revision to the EXPath Package spec to be stricter about semver.

**Comment by duncdrum** [comment]
always in favour of proper sem-versioning

**Comment by duncdrum** [comment]
so getting back to this, our handling of expath spec is already properly handling sem ver 2 as of https://github.com/eXist-db/exist/pull/2499 

We now also have the `legacy` option to deal with non semver compliant packages, i.e. publish a new release with sem-ver and keep the old ones as legacy.

The gist is awesome can we please have this, and use it for autodeploy as well, this has been a dark box of exist wizardry for too long.

**Comment by joewiz** [comment]
@duncdrum The "legacy" option we added in https://github.com/eXist-db/public-repo/pull/32 allowed us to look up apps by old "abbrev" values. It didn't have anything to do with semver.

Thus, I'm afraid we're still stuck in the same position. My semver script is strict and chokes on a string like "1.0". Here are the semver non-compliant strings we'd have to deal with in the (exist-db.org) public-repo - and these are just the apps, not to mention the eXist version strings, e.g., `2.2`

| app | version |
| - | - |
| bf-XForms | `1.4` |
| dh2016 | `0.1` |
| exist-sparql | `0.1-SNAPSHOT` |
| expath-bin-module | `1.0-SNAPSHOT` |
| expath-crypto-exist-lib | `0.7` |
| functx | `1.0` |
| geospatial | `0.1-SNAPSHOT` |
| jfreechart-showcase | `0.4` |
| mallet-topic-modeling | `0.3` |
| markdown | `0.6` |
| matumi | `0.5` |
| memsort | `1.0-SNAPSHOT` |
| stanford-corenlp | `0.1` |
| stanford-ner | `0.4` |
| tei-graphing | `0.1-SNAPSHOT` |
| wiki | `0.8` |
| xsltforms | `594` |

This boils down to the following unique values:

- `0.x`
- `0.x-SNAPSHOT`
- `1.0`
- `1.0-SNAPSHOT`
- `1.x`
- `594`

Of these, all but probably xsltforms could be handled by somehow padding the entries—according to rules like npm's coerce or clean (https://www.npmjs.com/package/semver#coercion):

- `0.1` -> `0.1.0`
- `0.1-SNAPSHOT` -> `0.1.0-SNAPSHOT`
- `1.0` -> `1.0.0`
- `1.0-SNAPSHOT` -> `1.0.0-SNAPSHOT`
- `1.1` -> `1.1.0`

I'm not sure whether I'd do this at the time of publishing or at the time of querying... I'd have to think through this...

The outlier is xsltforms, whose svn revision numbers we used but later switched to more semver-esque numbers. Any good ideas for `594` besides deleting the old not-even-trying-to-be-semver versions like this, and keeping only the trying-to-be-semver ones?

**Comment by duncdrum** [comment]
Imv, we should cut sem-ver compliant releases of all the apps under our control, and increase the minor version number. 

coerce those that we don't have control over seems reasonable,

`594` can go or become `0.0.1-594`

**Comment by joewiz** [comment]
@duncdrum This is a hell of a knotty problem. I'd like to solve it, but I don't want to break apps that expect packages to be available in the current repo at specific version strings, request URLs, etc. I think it might actually faster, cleaner, and less painful (!) to fork the package repository and strictly enforce semver 2.0 from day 1. Instead of "public-repo" I'd give the new app a different name like "package-repo"—the reason being that I do not want to muck with old apps or risk breaking people's apps that depend on today's behavior. If I had all of the pieces under my control, I'd work like hell to get this done in time for 5.0 final, but I think it's probably a group effort with core developers who could handle the java & expath side of things. So, practically speaking, a 6.0 time scale may be more reasonable. 

As to adding semver.xqm to core, I'm open to the idea. I guess I'd just open a PR adding the library to https://github.com/eXist-db/exist/tree/develop/exist-core/src/main/resources/org/exist/xquery/lib, right?

**Comment by duncdrum** [comment]
The problem is that as it is right now, folks have to to do improper sem-ver things to work around the kinks of public repo. I think this is worse than old code relying on old behaviour, or us breaking this. New code that is spec compliant should work in a predictable way, eg. RC3 > RC1

**Comment by joewiz** [comment]
A short path to resolve your RC issue would be to unpublished RCs.

**Comment by duncdrum** [comment]
Yeah lets do that then, the old xar are still preserved on Github after all

**Comment by joewiz** [comment]
@duncdrum Done.
