### ISSUE TITLE
Updating public-repo deletes all previously uploaded apps

### ISSUE THREAD

**Issue by adamretter** [eXist-db/public-repo#46]
This is a really silly design issue...

When you update an app, the `/db/app/<app-dir>` is deleted before the new version is installed. If the app stores its data inside its app dir then all its data is deleted.

One example of this, is this app, i.e. the `public-repo`. Updating the public repo causes all the apps on the public repo to be lost. This is quite ridiculous!

**Comment by line-o** [comment]
https://github.com/eXist-db/exist/issues/2309

**Comment by wolfgangmm** [comment]
I would argue that it is common practice that data to be preserved should reside in a safe location outside the collection (or directories) where an app is installed. This is the apps responsibility. For all larger apps, I have a separate `data.xar`. For public repo, it might be enough to change one line in the `config.xqm` to put the repo data into a safe location. I guess it was just forgotten.

In general, I would expect from a package manager to properly cleanup the old version before it installs a new one. This is what most systems do.

That said, one or two years ago there was a proposal to add a list of subcollections to be preserved to `repo.xml`. In some cases this might be useful and not difficult to implement.

**Comment by adamretter** [comment]
So the linux file systems base standard and the deb packaging standard between them define what will and won't be removed when a package is updated... basically the list of files which were installed by the package will be removed when the package is removed - so in this instance data files are not removed.

Unfortunately eXist-db's app management more blunt force than that, and tends to just try and delete entire collections.

It's fine saying apps should store data outside of `/db/apps` - but we don't seem to have told anyone, maybe not even ourselves, as our own apps (i.e. public-repo) have this problem. Also where should users store data, and how does that affect permissions etc? I think this needs to be properly thought out and a cohesive guide written.
