### ISSUE TITLE
provide explicit `/update` route

### ISSUE THREAD

**Issue by line-o** [eXist-db/public-repo#59]
At the moment the update script is the last module that is directly requested by clients.
I would propose to forbid any request to `/modules` by offering a explicit route to handle
package uploads `/update` or `/publish` would then forward to that endpoint.

This change requires only two small changes to controller.xql but we would need to discuss if this is possible without breaking other clients like packagemanager instances.

**Comment by joewiz** [comment]
update.xq can be disposed of. Legacy cruft.
