### ISSUE TITLE
[BUG] Packages returned in reverse order

### ISSUE THREAD

**Issue by bwbohl** [eXist-db/public-repo#84]
**Describe the bug**
The sort order of packages in request based on `$config:package-groups-doc` seems to be the wrong way around. While an ascending order of a packages semver is generally the expected behaviour for such a list, request to both https://exist-db.org/exist/apps/public-repo/public/apps.xml (or https://exist-db.org/exist/apps/public-repo/public/apps.xml?version=6.0.1) and http://exist-db.org/exist/apps/public-repo/find do not return the latest package version as expected, e.g.:

```xml
<app path="shared-resources-0.2.3.xar" size="1058865" sha256="bef5ee9dca0def9117baa1bfeeb2a433ae178477ef48293309a9fbb2829126d2">
    <name>http://exist-db.org/apps/shared</name>
    <title>Shared Resources: jquery, dojo, ace ...</title>
    <abbrev>shared</abbrev>
    <version>0.2.3</version>
    <author>Wolfgang Meier</author>
    <description>Shared resources used by other apps</description>
    <website />
    <license>GNU-LGPL</license>
    <type>library</type>
    <changelog />
    <older>
        <version path="shared-resources-0.2.4.xar" size="1059129"
            sha256="c5bedf498fc619a68b2dba6037e49f1311a50ca038956327bab1aafcb86481c4" />
        […omitted…]
        <version path="shared-resources-0.9.1.xar" size="1997412"
            sha256="6805a92c9d8b7a0cad691b268af7f40a24c1aa9eb14a0402d9c32df1da30f78c">
            <requires processor="http://exist-db.org" semver-min="3.0.4" />
        </version>
    </older>
</app>
```

Besides being a semantical inconsistency (`app/older/version` actually being a newer version), this also returns false packages when e.g. when calling e.g. http://exist-db.org/exist/apps/public-repo/find?abbrev=shared&processor=6.0.1 --> prompting for a download of `shared-resources-0.2.3.xar` instead of `shared-resources-0.4.2.xar`.

**Expected behavior**

Retrieve the latest compatible version of a package.

(retrieved by `$packages => head()`, e.g. in:
https://github.com/eXist-db/public-repo/blob/79406a0ed4896769bc96a223ab5d8c17a9145f65/modules/versions.xqm#L76-L85

Returning the last item of the array might be sufficient for find , while apps.xml maybe should list versions in reversed order.

**To Reproduce**
Call the above URLs.

**Context (please always complete the following information):**
- eXist-db Website 
- eXist-db Version: [6.0.1]
- App Version: [3.0.0]

**Comment by joewiz** [comment]
@bwbohl Thanks for reporting this. I've applied a hotfix to the exist-db.org instance. I'll submit a PR shortly.

**Comment by bwbohl** [comment]
@joewiz thanks for the really fast and hot fix ;-)
